### ISSUE TITLE
mods acting pretty weird on current master

### ISSUE THREAD

**Issue by ryan-sg** [3dfxdev/EDGE#64]
After getting a working build again after https://github.com/3dfxdev/hyper3DGE/pull/61 https://github.com/3dfxdev/hyper3DGE/pull/62 https://github.com/3dfxdev/hyper3DGE/pull/63  i set to work trying out things like doomforever and duke it out in doom.

In doomforever it seems that weapons that cause knockback make the knockback 'always on' (i.e. after firing rocket launcher my player always wants to backpedal cruise-control style)  pressing +forward will still go fwd

in duke it out in doom duke is very talkative, seems all his random quips are playing in a loop on repeat.  after blowing something up that cause guts, the blood and guts endlessly played on-screen as well.  and using the shrinkray and trying to step on an enemy made my display wig out constantly as the game wanted to pan down for the step, but also fought itself to recenter :-D

Perhaps these are all known type issues since it seems heavy construction is occurring, cheers!

**Comment by Corbachu** [comment]
I knew about a few, but not in detail like this. I'll check it out the very next time I have a chance to run them through VS's debugger. For reference, are they in WAD or EPK format? I've heard that RTS is a bit broken in WAD, but works fine either externally or in an EPK/PK3.

The display thing might be the force feedback - if you turn screen shake OFF does it still happen? What about weapon kick (game options)?

**Comment by ryan-sg** [comment]
Doom4ever and Duke it out in Doom are both in .wad format.  CeeJay had uploaded some newer vers since I last tried and the issues are about the same in either.

As luck would have it I did try weapon kick option and screen shake though they didn't seem to affect the problems from the mods at all.  THe screen shake I'm pretty sure is just from where the scripted sequence should happen that gets you to step on the now bug-sized enemies.

You're probably right about the RTS in wad thing, then :-)
One of the oldest edge mods I know of, qdoom, still faithfully works under master with no problems noticed as far as I can tell :-D

**Comment by Corbachu** [comment]
@ryan-sg :

> In doomforever it seems that weapons that cause knockback make the knockback 'always on' (i.e. after firing rocket launcher my player always wants to backpedal cruise-control style) pressing +forward will still go fwd

I have experienced this issue firsthand as well -- we need to find out what the last version of EDGE was that didn't experience this issue. Will follow up!

**Comment by Corbachu** [comment]
Being addressed; closing out due to age.
