### ISSUE TITLE
Possible Future Feature: INI Parsing for Engine Configuration (replacing edge2.cfg)

### ISSUE THREAD

**Issue by Corbachu** [3dfxdev/EDGE#66]
I would like to take some time and weigh in options about using the **INI format** as a replacement to our own CFG file that EDGE creates. I would like to move to something more robust as far as the configuration file is concerned. Using something more modern like INI over our engine-created CFG file could yield benefits, and increase neatness. 

Plus, I would like to move the CFG configuration as a whole into an '**autoexe.cfg**', much like how _QUAKE_ does it, so modders can set hard limits/switches/cvars/etc in their mods. EDGE would look for 'autoexec.cfg' in the mod folder or EPK root. _We don't need to support this for WAD format_, only external directories or EPK/PK3/PK7 archives.

I know we have a .preset file, but I feel that was only a temporary solution to what we want to achieve. 

- With INI, we could get rid of 'EDGE2.cfg' and just opt for edge-[user].ini, **much like how ZDoom does now**.
- Move the CFG configuration out of the root and use it for user-definable switches in mods, while renaming the file 'autoexec.cfg', much like how 'edge.preset' acts, but this would of course be more robust as it would technically clone EDGE2.cfg in some aspects.
- Library I am referencing below is built in C and is really lightweight, or we could create our own.
- Remove volatile 'edge.preset'

This would also give us the advantage when we eventually redo the EDGE IWAD interface as we can have per-engine INI configuration files (Doom, Rise of the Triad, Heretic, etc), or we could keep those contained to EDGE's existing CFG files. 

Fellow developers: I would like your suggestions and/or thoughts on this topic (@raa-eruanna @ChillyWillyGuru /etc)

This idea came from the following GIT project: [INIH](https://github.com/benhoyt/inih)

**Comment by JNechaevsky** [comment]
It is also small but important addion for Windows users who are using only standard notepad and/or not very friendly with 3rd part software. The benefit is simple - on Windows, .INI files are initially opened with notepad, while .CFG are not. So this way, config file will be editable by one (well, two actually) simple mouse clicks, which is a good way to go.  :thumbsup:

**Comment by Corbachu** [comment]
@JNechaevsky me and @ctd1500 are looking into integrating _TOML_ ([skystrife/cpptoml](https://github.com/skystrife/cpptoml)) for the main engine configuration file - trying to settle on a naming convention, which I'm thinking could be:

`[username]-edge-config.ini` 
And using _INI_ as the extension as opposed to _TOML_ - only because _INI_ is standard (though we could def change that) ;-)

As I've said before, _CFG_ _could_ be kept for an _autoexec.cfg feature_ (like _QUAKE_), or we could abandon the format altogether and just use _TOML_ for autoexec mod-specific variables/cvars.

**Comment by DaZombieKiller** [comment]
I would definitely be in support of TOML, it's essentially a standardized version of INI and is just overall far, far superior.

**Comment by usernameak** [comment]
I tried to implement this and found a major issue: #69.

**Comment by Corbachu** [comment]
Implemented and closing.
