### ISSUE TITLE
Doom, sector light to darkest linetypes

### ISSUE THREAD

**Issue by simc2** [3dfxdev/EDGE#76]
(Windows 8.1 64-bit, EDGE-x86-2.1.0pre-43-gcf829c9a8)

The Doom lineaction types 
194: SR Change sector light level to darkest next sector
173: S1 - " -
157: WR - " -
104: W1 - " -

In Edge they do not not set the tagged sector's light level to match the current darkest neghboring sector but they always set the light level to pitch black instead. I can't visually determine the light value more precisely than that it goes in between 0-23.

Test wad (Doom2 MAP01): [lights-to-darkest.zip](https://github.com/3dfxdev/EDGE/files/3980835/lights-to-darkest.zip)

**Comment by Corbachu** [comment]
Issue was resolved by Andrew Apted. Tested against v1.35 and v2.1.0(pre).
