### ISSUE TITLE
FEATURE: MP3 Support

### ISSUE THREAD

**Issue by Some1NamedNate** [3dfxdev/EDGE#86]
Software patents for the MP3 format expired in 2017. After finding out that older versions of EDGE had MP3 support, I thought I'd raise the alarm by saying, "MP3 is free now!"

Bringing back MP3 support would be great, which would mean that I can play MP3 music from `SIGIL_SHREDS.wad`, a paid enhancement to The Ultimate Doom MegaWAD "Sigil."

**Comment by Corbachu** [comment]
https://github.com/3dfxdev/EDGE/commit/d43980166490ed2e810d12cfd98863f3c41bf588

This was added as of the above commit. I have the SIGIL registered with the MP3 pack, when I first worked SIGIL support.

I'll wind this into playlists.DDF and test tonight. Provided all goes well, we will have a nice development release with other nifty features from @dashodanger and @Lobo, as well as other issues I've fixed related to those changes and additions.

**Comment by Corbachu** [comment]
Works with SIGIL_SHREDS - when added alongside SIGIL (and DOOM.wad if you are combining with DOOM2), for now the entries in PLAYLISTS must be changed to MP3 manually. I'm currently adding a scanner to quickly check for the other formats if they exist FIRST, regardless of what the LUMP type is defined in DDF. Releasing new build here shortly.

**Comment by Corbachu** [comment]
I have forgotten but it already works as such without needing to edit the playlist DDF for the SIGIL entries. 
I don't quite remember though if EDGE already had this behaviour or if this is a physFS enhancement.
Seems to be working alright, just doing more testing before closing the issue (loop music, test volume sliders, etc).

**Comment by Corbachu** [comment]
@dashodanger I've verified it works 100% in all cases, without the user needing to modify the playlist entries. Closing the PR! 

@Some1NamedNate Try it out with the latest 64-bit [devbuild ](https://devbuilds.drdteam.org/3dge/EDGE-x64-MSVC-2.1.0pre-214-gf16fbc560.7z), uploaded today (11/14/21) or at least later than r214.
